name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with: 
        username: ${{ secrets.DOCKER_USER_NAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN}}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      id: buildx

    - name: Build and push
      uses: docker/build-push-action@v2
      id: docker_build
      with:
        context: ./
        file: dev_staging_spaon/Dockerfile
        builder: ${{ steps.buldx.output.name }}
        push: true
        tags: ${{ secrets.DOCKER_USER_NAME }}/thai_yeu_huong

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        
