name: Build and Push Docker Image

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository

    - name: Set up Docker Buildx manually
      run: |
        docker buildx create --use
        docker buildx inspect --bootstrap

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push Docker image
      run: |
        docker buildx create --use
        docker buildx build --platform windows/amd64 -t your-dockerhub-username/thai_yeu_hai:latest .
        docker push your-dockerhub-username/thai_yeu_hai:latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        
