# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2
      
    - name: Set default value for status variable
      run: echo "status=success" >> $GITHUB_ENV

    - name: Restore dependencies
      run: |
        nuget restore dev_staging_spaon
        restore_status=$?
        if [ $restore_status -ne 0 ]; then
          echo "status=failure" >> $GITHUB_ENV
        fi
          
    - name: Build
      run: |
        msbuild /p:Configuration=Release dev_staging_spaon
        build_status=$?
        if [ $build_status -ne 0 ]; then
          echo "status=failure" >> $GITHUB_ENV
        fi
          
    - name: Prevent push to main on failure
      if: env.status == 'failure'
      run: exit 1
